/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.yandex.practicum.kafka.telemetry.event;

@org.apache.avro.specific.AvroGenerated
public interface SensorEventProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SensorEventProtocol\",\"namespace\":\"ru.yandex.practicum.kafka.telemetry.event\",\"types\":[{\"type\":\"record\",\"name\":\"ClimateSensorAvro\",\"fields\":[{\"name\":\"temperatureC\",\"type\":\"int\"},{\"name\":\"humidity\",\"type\":\"int\"},{\"name\":\"co2Level\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"LightSensorAvro\",\"fields\":[{\"name\":\"linkQuality\",\"type\":\"int\"},{\"name\":\"luminosity\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"MotionSensorAvro\",\"fields\":[{\"name\":\"linkQuality\",\"type\":\"int\"},{\"name\":\"motion\",\"type\":\"boolean\"},{\"name\":\"voltage\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"SwitchSensorAvro\",\"fields\":[{\"name\":\"state\",\"type\":\"boolean\"}]},{\"type\":\"record\",\"name\":\"TemperatureSensorAvro\",\"fields\":[{\"name\":\"temperatureC\",\"type\":\"int\"},{\"name\":\"temperatureF\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"SensorEventAvro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"hubId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"payload\",\"type\":[\"ClimateSensorAvro\",\"LightSensorAvro\",\"MotionSensorAvro\",\"SwitchSensorAvro\",\"TemperatureSensorAvro\"]}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends SensorEventProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = ru.yandex.practicum.kafka.telemetry.event.SensorEventProtocol.PROTOCOL;
  }
}